DROP TABLE IF EXISTS USERS CASCADE;
DROP TABLE IF EXISTS AUTHORITIES CASCADE;
DROP INDEX IF EXISTS ix_auth_username;

CREATE TABLE USERS
(
    username   VARCHAR(255) NOT NULL PRIMARY KEY,
    password   VARCHAR(255) NOT NULL,
    enabled    BOOLEAN      NOT NULL,
    first_name VARCHAR(255) NOT NULL
);

CREATE TABLE AUTHORITIES
(
    username  VARCHAR(50) NOT NULL,
    authority VARCHAR(50) NOT NULL,
    FOREIGN KEY (username) REFERENCES USERS
        ON DELETE CASCADE
);


CREATE UNIQUE INDEX ix_auth_username
    ON AUTHORITIES (username, authority);


INSERT INTO USERS (USERNAME, PASSWORD, ENABLED, FIRST_NAME)
VALUES ('user', '$2a$10$Pj/X44shWxyMiOUWFePIcOU5Pho.jWxQbGDixkFBxCn4M2Kar2GYG', true, 'Jack');

INSERT INTO USERS (USERNAME, PASSWORD, ENABLED, FIRST_NAME)
VALUES ('admin', '$2a$10$SqAvqhNjk6i5x7GM3bd9ZOqYw2b74GKFUda3h9yOeZhaGI2uF5fta', true, 'Jill');

INSERT INTO AUTHORITIES (USERNAME, AUTHORITY)
VALUES ('user', 'ROLE_USER');
INSERT INTO AUTHORITIES (USERNAME, AUTHORITY)
VALUES ('admin', 'ROLE_ADMIN');
